export const START_SEARCH_MOVIES_REQUEST = "START_SEARCH_MOVIES_REQUEST";
export const END_SEARCH_MOVIES_REQUEST = "END_SEARCH_MOVIES_REQUEST";
export const START_GET_MOVIE_DETAIL_BY_ID = "START_GET_MOVIE_DETAIL_BY_ID";
export const END_GET_MOVIE_DETAIL_BY_ID = "END_GET_MOVIE_DETAIL_BY_ID";
export const RESET_MOVIE_SEARCH = "RESET_MOVIE_SEARCH";